POST  http://localhost:8080/auth
Content-Type: application/json

{
    "username": "userABC",
    "password": "password123",
    "kid": "317f5558-1d84-4034-8a24-58dd5744163b"
}

###
GET http://localhost:8080/.well-known/jwks.json